In [ ]:
import pandas as pd
import numpy as np

**Usecase-1 Load all three csv datasets in Pandas Data frames and display first 5 records.**

In [ ]:
df_customers = pd.read_csv("customers.csv")
df_products = pd.read_csv("products.csv")
df_transactions = pd.read_csv("transactions.csv")

print("Customers Data:")
display(df_customers.head())

print("Products Data:")
display(df_products.head())

print("Transactions Data:")
display(df_transactions.head())

Customers Data:

,'custno','firstname','lastname','gender','age','profession','contactNo','emailId','city','state','isActive','createdDate','UpdatedDate'
0,1,Leslie,Bass,F,27,B,37307,endslost@everyma1l.org,Gibson,Dellwood,Y,2017-09-21 12:38:22,2017-10-18 12:12:28
1,2,Judy,Burks,M,53,S,84759,rfleming@hotma1l.co.uk,Suwanee,Trabue,Y,2017-05-22 05:29:22,2017-10-18 12:12:28
2,3,Marsha,Doyle,F,48,B,80932,arethe53@ma1lbox.net,Perry,Moxadarla,Y,2017-09-03 12:11:29,2017-10-18 12:12:28
3,4,Alexis,Battle,M,27,S,71701,ofcame@ma1lbox.org,Morven,Dennis,Y,2017-02-16 04:05:35,2017-10-18 12:12:28
4,5,Martha,Combs,F,49,B,83947,camedied@everyma1l.us,Ocilla,Greenwood,Y,2017-05-15 07:34:35,2017-10-18 12:12:28

Products Data:

,'productno','productName','Description','isActive','createdDate','UpdatedDate'
0,1,Product1,pgqorighfa,Y,2017-04-03 07:58:55,2017-10-18 12:12:38
1,2,Product2,lmndaaweth,Y,2017-09-21 12:38:31,2017-10-18 12:12:38
2,3,Product3,urifeubrhh,Y,2017-09-08 10:32:12,2017-10-18 12:12:38
3,4,Product4,rlpcjxfarp,Y,2017-05-22 05:29:27,2017-10-18 12:12:38
4,5,Product5,hzcpozsgfc,Y,2017-02-02 08:40:29,2017-10-18 12:12:38

Transactions Data:

   'txnno'            'txndate'  'custno'  'amount'  'productno' 'spendby'
0        1  2017-10-18 12:31:45       923      2559          376      Card
1        2  2017-10-18 12:31:45       219      1706          151      Card
2        3  2017-10-18 12:31:45       927      3462          707      Cash
3        4  2017-10-18 12:31:45       806       865          539      Card
4        5  2017-10-18 12:31:45       958      2494           25      Card

**Usecase-2 Display only those customers from CSV_s1, who purchased more than 3 products**

In [ ]:
purchase_counts = df_transactions.groupby("'custno'").size()
more_than_3 = purchase_counts[purchase_counts > 3].index

In [ ]:
frequent_customers = df_customers[df_customers["'custno'"].isin(more_than_3)]
display(frequent_customers)

,'custno','firstname','lastname','gender','age','profession','contactNo','emailId','city','state','isActive','createdDate','UpdatedDate'
3,4,Alexis,Battle,M,27,S,71701,ofcame@ma1lbox.org,Morven,Dennis,Y,2017-02-16 04:05:35,2017-10-18 12:12:28
85,86,Bonnie,McCall,M,37,S,70907,constantlyfire@gma1l.net,Screven,Farson,Y,2017-10-12 07:35:28,2017-10-18 12:12:28
166,167,Alice,Blake,F,58,B,22324,wherealways@b1zmail.biz,Homerville,Daisy,Y,2017-05-01 08:00:29,2017-10-18 12:12:28
186,187,Alan,Anthony,F,50,B,40487,calvarez@ma1l2u.us,Sunbury,Linn,Y,2017-05-25 04:59:16,2017-10-18 12:12:28
236,237,Dawn,West,F,26,B,75618,oncaves@everyma1l.biz,Adrian,Extension,Y,2017-03-04 01:29:08,2017-10-18 12:12:28
240,241,Derrick,Pearson,F,33,B,74138,acarpenter@b1zmail.com,Crescent,Grove,Y,2017-04-02 05:16:41,2017-10-18 12:12:28
320,321,Crystal,Le,F,64,B,37857,klawrence@hotma1l.biz,East Dublin,Thorn,Y,2017-08-31 06:11:45,2017-10-18 12:12:28
325,326,Heidi,Stanley,M,29,S,78822,bhull@everyma1l.us,Fayetteville,Garrell,Y,2017-08-30 04:10:06,2017-10-18 12:12:28
330,331,Cynthia,Harrison,F,49,B,53439,krush@gma1l.us,Mcintosh,Bradington,Y,2017-05-07 12:42:19,2017-10-18 12:12:28
355,356,Mitchell,Mason,M,37,S,45064,fromwhat@somema1l.us,Cecil,Lazelere,Y,2017-09-02 06:47:20,2017-10-18 12:12:28
390,391,Keith,Church,F,19,B,26859,tkeith@yah00.com,Collins,Stout,Y,2017-08-02 01:12:49,2017-10-18 12:12:28
536,537,Jake,Bush,F,23,B,80535,lsharpe@somema1l.us,Doraville,Springdale,Y,2017-03-10 03:37:40,2017-10-18 12:12:29
557,558,Lois,Todd,M,58,S,39051,rgarner@ma1lbox.org,Broxton,Cliffwood,Y,2017-10-03 05:37:28,2017-10-18 12:12:29
577,578,Christine,Murray,M,40,S,74244,aacevedo@somema1l.org,Sirmans,Darla,Y,2017-02-24 01:15:33,2017-10-18 12:12:29
708,709,Kyle,Haynes,F,44,B,30552,ecain@somema1l.com,Riverdale,Eastview,Y,2017-06-03 07:10:55,2017-10-18 12:12:29
734,735,James,Payne,F,39,B,30415,inhatch@b1zmail.biz,Gainesville,Hardesty,Y,2017-04-03 05:10:16,2017-10-18 12:12:29
752,753,Denise,Stokes,F,37,B,88779,textas98@b1zmail.org,Twin Peaks,Alburn,Y,2017-04-30 05:25:57,2017-10-18 12:12:29
827,828,Katrina,Barber,M,47,S,61069,whattook@everyma1l.us,Fort Oglethorpe,Detroit,Y,2017-04-14 06:49:04,2017-10-18 12:12:29
943,989,Ronald,Mayo,F,56,B,23161,redthrow@ma1lbox.com,Kite,Smithwood,Y,2017-10-04 04:16:09,2017-10-18 12:12:29

**Usecase-3 Display top 5 most demanded products from CSV_s1**

In [ ]:
product_counts = df_transactions["'productno'"].value_counts()

In [ ]:
top_5_products = product_counts.head(5)
print(top_5_products)

'productno'
427    5
768    5
82     5
900    5
113    4
Name: count, dtype: int64

In [ ]:
top_5_df = top_5_products.reset_index()
top_5_df.columns = ["'productno'", "'purchase_count'"]

top_5_details = pd.merge(top_5_df, df_products, on="'productno'", how='left')
display(top_5_details)

,'productno','purchase_count','productName','Description','isActive','createdDate','UpdatedDate'
0,427,5,Product427,rnqzbzweys,Y,2017-09-14 10:44:57,2017-10-18 12:12:38
1,768,5,Product768,hvfbltpjun,Y,2017-01-27 11:45:21,2017-10-18 12:12:39
2,82,5,Product82,ignxxzodmc,Y,2017-09-24 02:57:26,2017-10-18 12:12:38
3,900,5,Product900,ouoolyahlh,N,2017-01-10 12:35:30,2017-10-18 12:12:39
4,113,4,Product113,fktwodxvig,Y,2017-03-22 06:41:45,2017-10-18 12:12:38

**Usecase-4 Display top 5 transactions amount from CSV_s1**

In [ ]:
top_5_transactions = df_transactions.sort_values(by="'amount'", ascending=False).head(5)
display(top_5_transactions)

     'txnno'            'txndate'  'custno'  'amount'  'productno' 'spendby'
556      557  2017-10-18 12:31:46       670      4996          509      Card
305      306  2017-10-18 12:31:46       448      4992          427      Cash
574      575  2017-10-18 12:31:46       305      4981          549      Card
531      532  2017-10-18 12:31:46       230      4980          658      Card
232      233  2017-10-18 12:31:45       287      4966          685      Card

**Usecase-5 Display distinct professions from CSV_s1**

In [ ]:
df_customers["'profession'"].value_counts()

'profession'
B    500
S    500
Name: count, dtype: int64

**Usecase 6: Highest age in customers dataset**

In [ ]:
max_age=df_customers["'age'"].max()

df_customers[df_customers["'age'"]==max_age]

,'custno','firstname','lastname','gender','age','profession','contactNo','emailId','city','state','isActive','createdDate','UpdatedDate'
58,59,Randall,Lambert,F,64,B,41458,throwfrom@hotma1l.com,Broxton,Louise,Y,2017-10-10 09:57:25,2017-10-18 12:12:28
142,143,Nathan,Hamilton,F,64,B,81211,topull@everyma1l.us,Greenville,Willis,Y,2017-04-13 08:28:23,2017-10-18 12:12:28
163,164,Brianna,Vinson,M,64,S,48042,phahn@b1zmail.net,Avondale Estates,Palmeraway,Y,2017-09-03 04:24:27,2017-10-18 12:12:28
169,170,Marie,Hoffman,M,64,S,57181,islandtrees28@gma1l.org,Clarkston,Euclid,Y,2017-06-27 08:27:44,2017-10-18 12:12:28
201,202,Lewis,Wynn,M,64,S,64991,dpowell@somema1l.us,Dock Junction,Rains,Y,2017-03-23 05:02:27,2017-10-18 12:12:28
229,230,Jean,Singleton,M,64,S,30274,listwhat@gma1l.com,Rockmart,Warwick,Y,2017-08-06 10:57:05,2017-10-18 12:12:28
238,239,Alisha,Luna,F,64,B,28954,gweber@ma1l2u.com,Dupont,Skyline,Y,2017-08-21 04:36:04,2017-10-18 12:12:28
277,278,Christine,Vinson,M,64,S,89928,whilelibrary@gma1l.net,Lithonia,Whaley,Y,2017-03-26 11:58:14,2017-10-18 12:12:28
296,297,Daniel,Weiss,F,64,B,34243,adickerson@somema1l.com,Howell,Barkey,Y,2017-05-21 10:59:04,2017-10-18 12:12:28
297,298,Gary,Norman,M,64,S,89295,jwhitfield@everyma1l.biz,Ellabelle,Gilbert,Y,2017-04-21 09:40:21,2017-10-18 12:12:28
320,321,Crystal,Le,F,64,B,37857,klawrence@hotma1l.biz,East Dublin,Thorn,Y,2017-08-31 06:11:45,2017-10-18 12:12:28
353,354,Dana,Ross,M,64,S,27113,inplane@somema1l.co.uk,Lenox,Greenhouse,Y,2017-03-03 11:34:50,2017-10-18 12:12:28
393,394,Fred,Rowe,M,64,S,25741,cbattle42@hotma1l.co.uk,Ellaville,Gallia,Y,2017-05-03 03:40:29,2017-10-18 12:12:28
465,466,Andrea,Herring,M,64,S,33765,bgraham@ma1lbox.org,Cartersville,Montgomery,Y,2017-03-05 06:49:12,2017-10-18 12:12:29
500,501,Morgan,Donaldson,F,64,B,52553,ggordon8@yah00.biz,Elberton,Codell,Y,2017-08-15 01:08:02,2017-10-18 12:12:29
514,515,Cassandra,Cote,F,64,B,59376,lockwill0@hotma1l.co.uk,Hardwicke,Stacy,Y,2017-09-08 07:29:57,2017-10-18 12:12:29
520,521,Bonnie,Booker,F,64,B,69371,probablywho@somema1l.us,Morrow,Blaine,Y,2017-05-19 03:58:53,2017-10-18 12:12:29
586,587,Dallas,Santiago,F,64,B,52851,captainto@yah00.us,Potter,Raintree,Y,2017-09-11 05:44:25,2017-10-18 12:12:29
642,643,Charles,Baker,F,64,B,40232,computerto@gma1l.biz,Appling,Broadvue,Y,2017-10-16 10:55:29,2017-10-18 12:12:29
720,721,Charles,Lang,F,64,B,21836,vpearson@b1zmail.co.uk,New Rock Hill,Best,Y,2017-03-13 07:34:48,2017-10-18 12:12:29
754,755,Lewis,Beach,F,64,B,65873,rmendoza@hotma1l.co.uk,Holly Springs,Phillips,Y,2017-03-29 11:19:27,2017-10-18 12:12:29
763,764,Marvin,Stephens,M,64,S,29257,awilliams@hotma1l.us,Midway,Orders,Y,2017-03-18 07:03:32,2017-10-18 12:12:29
791,792,Erica,Randolph,M,64,S,57376,djones@b1zmail.com,Enigma,Springdale,Y,2017-09-29 12:48:13,2017-10-18 12:12:29
805,806,John,Mays,M,64,S,35395,cavesplane@hotma1l.org,Rebecca,Woodland,Y,2017-03-23 01:21:21,2017-10-18 12:12:29
814,815,Roger,Doyle,F,64,B,43933,ckey@b1zmail.com,Portal,Lavona,Y,2017-04-13 02:17:54,2017-10-18 12:12:29
849,850,Kendra,Case,M,64,S,32727,boontrying@everyma1l.co.uk,Poulan,Glena,N,2017-09-10 12:17:23,2017-10-18 12:12:29
941,987,Frank,Donaldson,F,64,B,82695,hatchwarp@somema1l.co.uk,Strongsville,Mcintire,Y,2017-04-08 03:08:06,2017-10-18 12:12:29
975,944,Vicky,Hawkins,M,64,S,51353,thernandez@everyma1l.us,Unionville,Blackstone,Y,2017-09-02 02:34:26,2017-10-18 12:12:29

**Usecase-7 Display custno, gender, age, profession, contactno, productno, productName,
txndate, spendby, amount from CSV_s1 for custno = 923
t**

In [ ]:
cutomer_923=df_customers[df_customers["'custno'"]==923].drop(["'firstname'","'lastname'","'emailId'","'city'","'state'","'isActive'","'createdDate'","'UpdatedDate'"],axis=1)

In [ ]:
cutomer_923

     'custno' 'gender'  'age' 'profession'  'contactNo'
922       923        F     46            B        25436

In [ ]:
tran_923=df_transactions[df_transactions["'custno'"]==923].drop(["'txnno'"],axis=1)

In [ ]:
merged = pd.merge(tran_923, df_products, on="'productno'", how="left")

In [ ]:
full_923=pd.merge(cutomer_923,merged,on="'custno'",how="inner").drop(["'Description'","'isActive'","'createdDate'","'UpdatedDate'"],axis=1)
full_923

,'custno','gender','age','profession','contactNo','txndate','amount','productno','spendby','productName'
0,923,F,46,B,25436,2017-10-18 12:31:45,2559,376,Card,Product376
1,923,F,46,B,25436,2017-10-18 12:31:46,2303,113,Card,Product113
2,923,F,46,B,25436,2017-10-18 12:31:46,4553,644,Cash,Product644

**Usecase-8 Load all three PSV (pipe separated values) dataset in Pandas Data frames and
display first 5 records**

**Usecase-9 Load all three JSON datasets in Pandas Data frames and display first 5 records**

In [ ]:

json_customers = pd.read_json("customers.json", lines=True)
json_products = pd.read_json("products.json", lines=True)
json_txns = pd.read_json("transactions.json", lines=True)

display(json_customers.head())
display(json_products.head())
display(json_txns.head())

,custno,firstname,lastname,gender,age,profession,contactNo,emailId,city,state,isActive,createdDate,UpdatedDate
0,1,Dai,Noble,2,53,Human Resources,1644101928099,eu.lacus.Quisque@loremac.com,Berlin,Berlin,1,2017-03-01,2018-08-25
1,2,Kay,Wise,2,26,Public Relations,1674031917099,ridiculus@Sednunc.ca,Oldenzaal,Overijssel,2,2017-04-10,2018-08-30
2,3,Amir,Pace,1,43,Customer Relations,1636050509999,quam.Pellentesque@erat.edu,Cobourg,Ontario,2,2017-03-04,2018-09-18
3,4,Sebastian,Lopez,2,32,Customer Relations,1666010108899,magna@venenatis.net,Te Awamutu,NI,1,2016-12-17,2018-09-12
4,5,Brian,Maddox,1,40,Quality Assurance,1646080399299,ac.facilisis@Duis.com,Greater Sudbury,Ontario,2,2017-02-18,2018-05-13

   productno     productName Description  isActive createdDate UpdatedDate
0        100        Vauxhall        four         2  2016-11-21  2017-11-09
1        101          Toyota         six         2  2017-10-03  2017-11-13
2        102  General Motors         two         1  2017-09-18  2017-11-03
3        103         Renault       eight         2  2017-10-05  2017-11-13
4        104        Kenworth       three         1  2017-05-03  2017-11-04

   txnno     txndate  custno  amount  productno  spendby
0      1  2018-07-31      71     181         19        2
1      2  2017-04-02      44     401         48        2
2      3  2018-01-31      45    1808         44        2
3      4  2018-04-02      62      65         22        2
4      5  2017-08-17      88    1149         74        2

**Usecase-10  Load all three XML datasets in Pandas Data frames and display first 5 records**

In [ ]:
xml_customers = pd.read_xml("customers.xml")
xml_products = pd.read_xml("products.xml")
xml_txns = pd.read_xml("transactions.xml")
display(xml_customers.head())
display(xml_products.head())
display(xml_txns.head())

,custno,firstname,lastname,gender,age,profession,contactNo,emailId,city,state,isActive,createdDate,UpdatedDate
0,1,Teegan,Hubbard,2,33,Human Resources,1681121691699,nibh.Quisque@placerat.com,Galashiels,Selkirkshire,1,2016-12-07,2018-09-05
1,2,Deacon,Briggs,2,54,Customer Relations,1631082682999,facilisis.eget@Nullaeu.com,Lens-Saint-Remy,LU,1,2017-04-26,2018-06-04
2,3,Mallory,Shelton,1,57,Customer Relations,1627011572699,Curabitur.ut@Nullatempor.edu,North Shore,NI,1,2017-01-02,2018-08-01
3,4,Quinn,Clements,2,43,Media Relations,1618122268999,metus.Vivamus.euismod@urna.edu,Heredia,H,1,2017-02-11,2018-07-18
4,5,Arthur,Hurst,2,41,Tech Support,1681021022799,in@commodoipsum.org,San Diego,Cartago,2,2017-03-30,2018-05-19

   productno     productName Description  isActive createdDate UpdatedDate
0        100  Hyundai Motors       eight         2  2017-10-01  2017-11-04
1        101           Honda       eight         1  2017-04-10  2017-11-11
2        102             GMC       three         2  2017-02-09  2017-11-17
3        103           Lexus       eight         2  2017-06-01  2017-11-04
4        104           Smart        five         2  2017-08-10  2017-11-16

   txnno     txndate  custno  amount  productno  spendby
0      1  2018-09-16       6     576         73        1
1      2  2018-02-11      96    1038         40        2
2      3  2017-06-13      17     673          2        1
3      4  2017-07-25      89    1284        100        2
4      5  2017-06-15       9    1685         56        2